{% set name = "winloop" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b967a8bcc45cb9a6845e5d4fc77a493b8b9928b44b9230ff336b9b10ae399132
  patches:
    - patches/0001-unvendor-libuv.patch

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=60
    - wheel
    - cython >=3.1.2
    - pip
    - libuv {{ libuv }}
  run:
    - python
    - libuv

{% set skip_keywords = [
# >       self._run_server_test(test, use_ssl="yes")
# E   AssertionError: True is not false
  "test_create_ssl_server_manual_connection_lost",
# E   AssertionError: Lists differ: [(<Ad[239 chars]('23.220.75.245', 80)), 
# (<AddressFamily.AF_INE[769 chars]80))] != [(<Ad[239 chars]('23.192.228.84', 80)), (<AddressFamily.AF_INE[769 chars]80))]
  "test_getaddrinfo",
# ConnectionResetError: Connection lost
  "test_write_huge_stdin",
# >  self.assertEqual(so.read(), b"out" + NL)
# E  AssertionError: b'' != b'out\n'
  "test_process_streams_redirect",
# >  raise CalledProcessError(retcode, cmd)
# E  subprocess.CalledProcessError:
  "test_signals_fork_in_thread",
# AssertionError: 0.2007368999766186 not less than 0.07
  "test_call_at"
] %}

test:
  source_files:
    - tests
    - mypy.ini
    - .flake8
  imports:
    - winloop
  commands:
    - pip check
    - pytest -v tests -k "not ({{ skip_keywords | join(' or ') }})"
  requires:
    - pip
    - pytest
    - pyopenssl >=23.0,<25.2

about:
  home: https://github.com/Vizonex/Winloop
  summary: Windows version of uvloop
  license: Apache-2.0 AND MIT
  license_family: OTHER
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  description: Windows version of uvloop
  doc_url: https://github.com/Vizonex/Winloop/blob/main/README.md
  dev_url: https://github.com/Vizonex/Winloop

extra:
  recipe-maintainers:
    - owenlamont
